# .github/workflows/local-images.yml
# Author: Daniel M. Zimmerman
# Created: 2024-12-16
# Modified: 2024-12-16

# This workflow builds the local images to make sure
# they build successfully.

name: Build Local Images

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Free Up Space
        run: |
          rm -rf /opt/hostedtoolcache

      - name: Build Binder Image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Build API Server Image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.api
          platforms: linux/amd64,linux/arm64

      - name: Build JupyterLab Image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.jupyter
          platforms: linux/amd64,linux/arm64
